const snekfetch = require("snekfetch");
const { Command } = require("../structures");

const { mashapeKey } = require("../config.json");

module.exports = class DefineWordCommand extends Command {
  constructor(client) {
    super(client, {
      name: "define",
      description: "Searches up definitions for the given word.",
      syntax: "define <...WORD>",
      args: 1
    });
  }
  async run(msg, args) {
    const word = args.join("_").toLowerCase();
    const res = await snekfetch
      .get(`https://wordsapiv1.p.mashape.com/words/${word}`)
      .set("X-Mashape-Key", mashapeKey);

    const data = JSON.parse(res.body);
    if (data.message) {
      return msg.channel.send(`${msg.author}, failed to get definition info for ${args.join(" ")}: \`${data.message}\``);
    }
    return msg.channel.send({
      embed: {
        title: `Definitions for **${word.split("_").join(" ")}**`,
        description: data.results
          .map((result, index) => `${index + 1}) ${result.partOfSpeech}: *${result.definition}*`)
          .join("\n"),
        footer: { text: "Generated by Quasar" },
        timestamp: Date.now()
      }
    });
  }
};