const { Command } = require("../structures");

module.exports = class NationCommand extends Command {
  constructor(client) {
    super(client, {
      name: "nation",
      description: "Shows the specified nation",
      syntax: "nation <...NATION>",
      args: 1
    });
  }
  async run(msg, [...nation]) {
    nation = nation.join("_").toLowerCase();
    const startTime = process.hrtime();
    try {
      const { NATION: data } = await this.client
        .request(`https://www.nationstates.net/cgi-bin/api.cgi?nation=${nation}&q=wa+region+lastactivity+category+fullname+flag`);

      const embed = {
        color: 0x1772c9,
        title: data.FULLNAME[0],
        description: data.CATEGORY[0],
        url: `https://nationstates.net/nation=${nation}`,
        thumbnail: { url: data.FLAG[0] },
        fields: [
          {
            name: "Region",
            value: data.REGION[0]
          },
          {
            name: "WA Status",
            value: data.UNSTATUS[0]
          },
          {
            name: "Active",
            value: data.LASTACTIVITY[0]
          }
        ],
        footer: { text: "Generated by Quasar" }
      };
      const diff = process.hrtime(startTime);
      const diffString = diff[0] > 0 ? `\`${diff[0]}\`s` : `\`${diff[1] / 1e6}\`ms`;
      console.log("[DEBUG] Time taken:", diffString);
      return msg.channel.send({ embed });
    } catch (err) {
      return msg.channel.send(`There was an error with your request: \`${err.message}\``);
    }
  }
};